id: IB24E6EB6
legacy_id: P002985
ocr_import_info:
  bdrc_scan_id: W29254
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T16:05:36'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T10:20:23.928788+00:00'
last_modified: 2022-09-02 18:20:48.696298
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W29254
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW29254
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དཔལ་འབྲུག་པ་རིན་པོ་ཆེ་ཞབས་དྲུང་ངག་དབང་རྣམ་རྒྱལ་གྱི་རྣམ་ཐར།
  author: དྲུང་ཆེན་སངས་རྒྱས་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.9328210365312928
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1GS105482:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1GS105482
      total_pages: 420
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1GS105482.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9328210365312928
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
